language: python
dist: bionic

stages:
  - linting
  - test

cache:
  pip: true

before_install:
  - pip install 'poetry>=1.0.0b1'

install:
  - poetry install -v -E yaml

script:
  - pytest --cov-report xml --cov-report term-missing --cov-append --cov cp2k_input_tools tests/

after_success:
  - codecov

jobs:
  include:
    - python: "3.6"
    - python: "3.7"
    - stage: linting
      python: "3.6"
      install:
        - pip install pre-commit
        - pre-commit install-hooks
      script:
        - pre-commit run --all-files

before_deploy:
  - poetry build

deploy:
  provider: script
  script: poetry publish --username "$PYPI_USER" --password "$PYPI_PASSWORD"
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_PYTHON_VERSION == 3.7"

env:
  global:
    secure: U20X+5LG9lA8R7JOBzsGEwLTPSGn8oAebFvbxSSf8U67Ij0NOn/yNJcJgc5zyeHy0CGmFvH6EbuYcTM6Eepyk1r7T4gN1QOU7Q2ycbyny4kH/VeFx1/B8NF/gn/zsVLqd3uY67uO0fGYOwImDlU8SSrxpr5nmN+5uHzvfCE31evYmFKNFdwqHsNSPEx5CefOt7+49i7wRHvqMCbA22gJ+l65yoo+mEcApq+c3sHY27VYyYHlFSOi8uTUe6QGyJNUWkDy/fKuH7elDMzjib5CXQN+nZqj8xY/RSCVViYU9FLRKCRt0dLApsuYju/kDZMxH2mGMXvq2cAApii0ucYJFvnzR6peKlGjy1FafpgxQlr0jK3eD45R13YqW4I2yN/1dCrbPM+OJP75/n6gK5mcLiIj4sp7a6RQWGHw53VFKVjgCgk8Ur4RzjVmTgbROCEW7Ja520gkZkAe8t+NDdugU71np/4Ov0bXooKE5OfVK2S21w38X1lGGL6fi8xu0kJ0H2vjmLxG+VZ6xWumDECpAJPJtMgWSzxUIK5tpLddoxuYhjxnPzMruLphmc02h5a5YeMvG18xslLFzVSd8aaM0Skw1WO5SX7XCUTuQ7Fk2HRL+X6lsE1L0IDnEUtAhNmoJuCx1HIZTOLtznUHiS8hIBjJTJceDk2xn6IZBpCWW7k=
